# This file was generated by GoReleaser. DO NOT EDIT.
cask "spackle" do
  version "0.4.3"

  on_macos do
    on_intel do
      url "https://github.com/A2-ai/spackle/releases/download/v#{version}/spackle_Darwin_x86_64.tar.gz"
      sha256 "08823c7a3ffa2fc872527682abbee7a620682a44de2cb9713d48695b4c733c0d"
    end
    on_arm do
      url "https://github.com/A2-ai/spackle/releases/download/v#{version}/spackle_Darwin_arm64.tar.gz"
      sha256 "769a78253593b8e0b03d2b7cd716d5d441b1aa8e3b1f89d5451357866fc7088c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/A2-ai/spackle/releases/download/v#{version}/spackle_Linux_x86_64.tar.gz"
      sha256 "996fbf676f7accad9342714c8fad7837f4d5bc330a7e8da2034c8ef0b20fa340"
    end
    on_arm do
      url "https://github.com/A2-ai/spackle/releases/download/v#{version}/spackle_Linux_arm64.tar.gz"
      sha256 "ac376d9f515e1bae0cde9ee1810c3f71259b4e5b1944135c5a569623ae8c3c74"
    end
  end

  name "spackle"
  desc "A frictionless project templating tool."
  homepage "https://github.com/a2-ai/spackle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spackle"

  # No zap stanza required

end
