# This file was generated by GoReleaser. DO NOT EDIT.
cask "spackle" do
  version "0.5.0-rc1"

  on_macos do
    on_intel do
      sha256 "506a2e8bfb293765036bf246a6f8bb3040b050ebbd7ba98484b7ec850d9112fb"
      url "https://github.com/A2-ai/spackle/releases/download/v#{version}/spackle_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f3c0c34e7ac36d84901bd44903945b7a15a15aaf2f0d3a6f2f8368dbfcf540bf"
      url "https://github.com/A2-ai/spackle/releases/download/v#{version}/spackle_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e76de9f64442b383b8a1d3150a90a435335f87a6473eebe338bb5b0987277766"
      url "https://github.com/A2-ai/spackle/releases/download/v#{version}/spackle_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f738e30206f93a67d0d7dd5323afc30f623432471960ef3d066690c04d0dda80"
      url "https://github.com/A2-ai/spackle/releases/download/v#{version}/spackle_Linux_arm64.tar.gz"
    end
  end

  name "spackle"
  desc "A frictionless project templating tool."
  homepage "https://github.com/a2-ai/spackle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spackle"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spackle"]
    end
  end

  # No zap stanza required

end
