# This file was generated by GoReleaser. DO NOT EDIT.
cask "spackle" do
  version "0.5.0-rc1"

  on_macos do
    on_intel do
      sha256 "9583effa85859ea0d9b12ea848df3444d9b28e7b91003ff48fb3fe1dae1e8fac"
      url "https://github.com/A2-ai/spackle/releases/download/v#{version}/spackle_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0f6422d3b633528875c43c1d26cf0eb3bae341c651809c0384ad4c4ef4931f10"
      url "https://github.com/A2-ai/spackle/releases/download/v#{version}/spackle_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3412260f74ef8d2e22b6f4f111d001cc766c074b3ad365d315d323eda040bdf6"
      url "https://github.com/A2-ai/spackle/releases/download/v#{version}/spackle_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ffd1424b9e4a51bff8a769bbc0a9a14bab3f45bcf7d3f012cdfa18efcfbd71a7"
      url "https://github.com/A2-ai/spackle/releases/download/v#{version}/spackle_Linux_arm64.tar.gz"
    end
  end

  name "spackle"
  desc "A frictionless project templating tool."
  homepage "https://github.com/a2-ai/spackle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spackle"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spackle"]
    end
  end

  # No zap stanza required

end
